name: Backpacks
authors: [drtshock, kashike, mbaxter]
website: ${project.url}

version: ${project.version}
main: com.drtshock.playervaults.PlayerVaults
softdepend: [Vault, Multiverse-Inventories, PlaceholderAPI]
api-version: 1.21

commands:
  bp:
    description: Open a vault.
    aliases: [vault, chest, playervaults, vc, backpack]
  bpdel:
    description: Delete a vault.
    aliases: [vaultdel]
  bpsign:
    description: Manage vault signs.
    aliases: [vaultsign]
  bpconvert:
    description: Convert other plugins to PlayerVaultsX.
    aliases: [vaultconvert]
  bpreload:
    description: Reload the configuration and language files.
    permission: playervaults.admin
  bphelpme:
    description: Pastes debug info to get better assistance.
    permission: playervaults.admin
  bpconsole:
    description: Console-only commands
    permission: playervaults.console

permissions:
  playervaults.admin:
    description: Grants access to admin commands for vaults.
    default: op
  playervaults.bypassblockeditems:
    description: Grants access to bypass blocked vault items.
    default: op
  playervaults.commands.use:
    description: Use the command
    default: true
